### ISSUE TITLE
Tfa9874 missing in codec folder ?

### ISSUE THREAD

**Issue by testingweb624** [edk2-porting/linux-snapdragon#5]
Hi,
Why you haven't added tfa9874 codec driver in kernel yet. This might add sound to OP6T fajita device.

Can you please add that ?

**Comment by J0SH1X** [comment]
fajita uses tfa9894 not 9874 there is no driver available apart from the one from caf which wont be pushed upstream for obvious reasons

**Comment by BigfootACA** [comment]
it is expected to be added today, please wait

**Comment by testingweb624** [comment]
> fajita uses tfa9894 not 9874 there is no driver available apart from the one from caf which wont be pushed upstream for obvious reasons

https://gitlab.com/sdm845-mainline/linux/-/merge_requests/25#note_950643676

Plz read this, where amartinz said fajita op6t uses tfa9874 not tfa989x. Both are very different. Tfa989x is recently added in pmos kernel for shift6mq phone .

**Comment by testingweb624** [comment]
Idk who is right.. What all I want is sound in op6t.. So that we can enjoy the beauty of powerful phone op6t. Isn't it. Thanks BigfootAcA in advance

**Comment by J0SH1X** [comment]
> > fajita uses tfa9894 not 9874 there is no driver available apart from the one from caf which wont be pushed upstream for obvious reasons
> 
> https://gitlab.com/sdm845-mainline/linux/-/merge_requests/25#note_950643676
> 
> Plz read this, where amartinz said fajita op6t uses tfa9874 not tfa989x. Both are very different. Tfa989x is recently added in pmos kernel for shift6mq phone .

well my sound is working so i know its tfa9894, but to proove here check dts yourself

https://gitlab.com/sdm845-mainline/linux/-/blob/sdm845/5.17-release/arch/arm64/boot/dts/qcom/sdm845-oneplus-fajita.dts#L36

**Comment by testingweb624** [comment]
Hmm its look like you are right, it's already been added. May be amartin by mistakenly wrote 74 .. :)

So have you pushed MR ?

**Comment by testingweb624** [comment]
I can see tfa9890 is added to this kernel. We op6t peoples are waiting for tfa9894 plz.

**Comment by J0SH1X** [comment]
There is no 9894 driver for mainline.
There is only the CAF driver i made compile which isnt pushed Into the
kernel for obvious reasons.
If you want to use the CAF driver clone github.com/j0sh1x/tfa98xx
export ARCH=arm64
Export KDIR=pathtoyourkernelsource
make
sudo cp tfa98xx.cnt /lib/Firmware
sudo insmod snd-soc-tfa98xx.ko

identicons ***@***.***> schrieb am Sa., 21. Mai 2022, 11:46:

**Comment by testingweb624** [comment]
But Caleb said in we are open to MR this tfa98xx driver if we want this in sdm845-mainline kernel in postmarketos.

See here, 

https://gitlab.com/sdm845-mainline/linux/-/merge_requests/25#note_954616210

**Comment by J0SH1X** [comment]
> But Caleb said in we are open to MR this tfa98xx driver if we want this in sdm845-mainline kernel in postmarketos.
> 
> See here,
> 
> https://gitlab.com/sdm845-mainline/linux/-/merge_requests/25#note_954616210

well caleb said to me they have no iontrest in that driver cause it needs a firmware and he keopt telling me drgit works on a driver for fajita

**Comment by testingweb624** [comment]
@BigfootACA  can you push tfa98xx driver from caf plz.
That will resolve sound problem for all goodix tfa having devices like oneplus 6t.

**Comment by J0SH1X** [comment]
Well we wont merge it , Compile it externally like i explained or GTFO

identicons ***@***.***> schrieb am Mo., 23. Mai 2022, 13:19:

**Comment by J0SH1X** [comment]
Or just wait for me to finish my ubuntu rootfs later it will be flashable
through twrp

Aljoshua Hell ***@***.***> schrieb am Mo., 23. Mai 2022, 13:53:

**Comment by noobimpostor2** [comment]
@testingweb624 @BigfootACA anyone suceed to add audio in op6t fajita windows?😶

**Comment by qaz6750** [comment]
@noobimpostor2 Audio requires drivers and ADSP, AUDD to work properly, but currently there may be a lack of maintenance personnel and no active maintenance
